// The patron kami of each section of the wiki, 16×16 on the game's icon palette (iconsWorld.ts › PAL): three tones a material,
// lit from the top left, the 1 px lacquer outline `k`. Pure data; Kami.astro turns a grid into crisp SVG at build time.
import { ic, type Icon } from '../../../awo/client/src/art/iconsWorld.ts';

/** Inari's white fox (kitsune): paper fur, red ears and eye marks, the gold jewel of a messenger. Mundos. */
export const INARI = ic([
  '..kk........kk..',
  '.kWWk......kWWk.',
  '.kWRWk....kWRWk.',
  '.kWRRWk..kWRRWk.',
  '.kWWWWkkkkWWWWk.',
  '.kWWwwwwwwwwWpk.',
  '.kWwwwwwwwwwwpk.',
  '.kWwkwwwwwwkwpk.',
  '..kwwRwwwwRwpk..',
  '..kwwwwwwwwwpk..',
  '...kwwwwwwwpk...',
  '...kwwwkkwwpk...',
  '....kwwkYkpk....',
  '.....kwwwwk.....',
  '......kppk......',
  '.......kk.......',
]);
/** Susanoo's storm sword (Kusanagi) over a wave: steel blade, gold tsuba, indigo water. Bestiario. */
export const SUSANOO = ic([
  '............kkk.',
  '...........kSWk.',
  '..........kSSsk.',
  '.........kSSsk..',
  '........kSSsk...',
  '.......kSSsk....',
  '......kSSsk.....',
  '....kkkSsk......',
  '...kYyykk.......',
  '..kYyoykk.......',
  '.kLLkykkxk......',
  'kLllLkkkxk......',
  'kLlllLLnkk......',
  'kllnnlllnk......',
  'kLllnnnlnk......',
  '.kkkkkkkk.......',
]);
/** Raijin's taiko drum: red body, gold rims and studs, the mitsudomoe on its skin and a bolt of fire. Jefes. */
export const RAIJIN = ic([
  '......kFk.......',
  '.....kFfk.......',
  '....kFfkk.......',
  '...kkFkkkkkk....',
  '..kYyYkWWWwYk...',
  '.kYyykWwkWwwyk..',
  '.kYyykWkwkwwyk..',
  '.kYyykwwWkwwyk..',
  '.kYyykwkwwkpyk..',
  '.kYyykwwkwwpyk..',
  '.kYyoykwwwppyk..',
  '.kyyoyykpppyok..',
  '..kRrqyyyyyok...',
  '..kRrrrqqqqok...',
  '...kkRrrqqkk....',
  '.....kkkkk......',
]);
/** Hachiman's kabuto: lacquer bowl, gold maedate crest, red cords, the neck guard's plates. Clases. */
export const HACHIMAN = ic([
  '.....kYYYk......',
  '....kYyyyYk.....',
  '...kkYyoyYkk....',
  '..kKxkYyykxxk...',
  '.kKxxxkYykxxxk..',
  '.kKxxxxkkxxxxk..',
  'kKxxxxxxxxxxxxk.',
  'kKKKKKKKKKKKKKk.',
  'kRrrrrrrrrrrrqk.',
  '.kKxxxxxxxxxxk..',
  '.kRrrrrrrrrrqk..',
  '.kKxxxxxxxxxxk..',
  '.kRrrrrrrrrrqk..',
  '..kkkkkkkkkkk...',
  '....kWk..kWk....',
  '.....k....k.....',
]);
/** Amaterasu's sun mirror (Yata no Kagami): a gold disc with rays, the paper-bright face of the mirror. Objetos. */
export const AMATERASU = ic([
  '.......kk.......',
  '..k...kYYk...k..',
  '.kYk.kYyyYk.kYk.',
  '..kYkYyWwyYkYk..',
  '...kYyWWwwyYk...',
  '..kYyWWWwwwyYk..',
  '.kYyyWWwwwwyyYk.',
  'kYYyyWwwwwpyyYYk',
  'kYyyyWwwwppyyyyk',
  '.kYyywwwpppyyok.',
  '..kYyywpppyyok..',
  '...kYyyyyyyok...',
  '..kYkYyyyyokYk..',
  '.kYk.kYyyok.kYk.',
  '..k...kook...k..',
  '.......kk.......',
]);
/** Ebisu's sea bream (tai): red scales lit on the back, gold fins, a steel eye. Economía. */
export const EBISU = ic([
  '................',
  '..........kk....',
  '....kkkkkkYYk...',
  '..kkRRRRRRkyYk..',
  '.kRRrrrrrrRkyYk.',
  'kRRrkWrrrrrRkyk.',
  'kRrrkkrrrrrrqkk.',
  'kRrrrrrrrrrqqYk.',
  'kRrrrrrrrrqqkyYk',
  '.kRrrrrrrqqkyyYk',
  '..kkrrrqqqkkyok.',
  '....kkqqqkk.ok..',
  '....kYyykk..k...',
  '...kYyokk.......',
  '....kok.........',
  '.....k..........',
]);
/** The torii, as the game draws it: kasagi swept up, red shimaki, gold plaque, nuki past the pillars, stone feet. Arte. */
export const TORII = ic([
  'k............k..',
  'kKkkkkkkkkkkkKk.',
  '.kxxxxxxxxxxxxk.',
  '..kRrrrrrrrrrk..',
  '..kqrrkYykrrqk..',
  '...kRrkykkrqk...',
  '...kRrkYykrqk...',
  '..kRrrrkkrrrqk..',
  '..kRrrrrrrrrqk..',
  '...kRrkkkkrqk...',
  '...kRrk..kRqk...',
  '...kRrk..kRqk...',
  '...kRrk..kRqk...',
  '...kxxk..kxxk...',
  '..kSsstk.kSsstk.',
  '..kkkkkk.kkkkkk.',
]);
/** The onmyōji's shikiban: a lacquered square earth plate under the round heaven plate, the gold Seiman star. Técnico. */
export const ONMYOJI = ic([
  '.kkkkkkkkkkkkkk.',
  'kKxxxxxxxxxxxxxk',
  'kxxxkkkkkkkkxxxk',
  'kxxkYyyyyyyykxxk',
  'kxkYyyyYyyyyykxk',
  'kxkYyyYoYyyyykxk',
  'kxkYyyYyYyyyykxk',
  'kxkYYoYoYoYYykxk',
  'kxkYyyYoYyyyykxk',
  'kxkYyyYyoYyyokxk',
  'kxkYyYyyyYyyokxk',
  'kxkyyoyyyyoookxk',
  'kxxkyoooooookxxk',
  'kxxxkkkkkkkkxxxk',
  'kKxxxxxxxxxxxxxk',
  '.kkkkkkkkkkkkkk.',
]);
/** Fūjin's wind bag: a bulging indigo sack tied with rope, the wind rushing out as paper streaks. Progresión. */
export const FUJIN = ic([
  '........kk......',
  '.......kAak.....',
  '......kkaak.....',
  '....kkLLkkkk....',
  '...kLLllLLLLk...',
  '..kLLlllllllLk..',
  '.kLLllllllllnlk.',
  '.kLlllllllnnnlk.',
  'kLllllllllnnnnlk',
  'kLlllllllnnnnnlk',
  'kLllllllnnnnnnlk',
  '.kllllnnnnnnnnk.',
  '.kWwkllnnnnnnk..',
  'kWwwpkknnnnkk...',
  '.kppk.kkkkk.....',
  '..kk............',
]);
/** Daikokuten's lucky mallet (uchide no kozuchi): a wooden head banded in gold on its handle, two coins struck out. Interfaz. */
export const DAIKOKU = ic([
  '..kkkkkkkkk.....',
  '.kBbbbbbbbbk....',
  'kBBYyyyyyyyyk...',
  'kBbyoyyyyyydk...',
  'kBbbbbbbbbbbdk..',
  'kBbbbbbbbbbbdk..',
  'kBbYyyyyyyyydk..',
  'kbbyooooooyddk..',
  '.kbbbbbbbbbddk..',
  '..kkkkkBbkkkk...',
  '......kbdk.kYk..',
  '......kbdkkYyYk.',
  '......kbdkYykYk.',
  '......kbdkkYyk..',
  '......kbdk.kk...',
  '......kkkk......',
]);

export const KAMI: Record<string, { icon: Icon; name: string; line: string }> = {
  inari: { icon: INARI, name: 'Inari', line: 'y sus kitsune guardan los caminos entre mundos' },
  susanoo: { icon: SUSANOO, name: 'Susanoo', line: 'el dios de la tormenta que mató a la serpiente de ocho cabezas' },
  raijin: { icon: RAIJIN, name: 'Raijin', line: 'el trueno de los tambores: cada jefe principal es su tormenta' },
  hachiman: { icon: HACHIMAN, name: 'Hachiman', line: 'el dios de la guerra y de los arqueros vela por los cuatro héroes' },
  amaterasu: { icon: AMATERASU, name: 'Amaterasu', line: 'el oro del sol y del kintsugi: lo roto, reparado, vale más' },
  ebisu: { icon: EBISU, name: 'Ebisu', line: 'el dios de los pescadores y el comercio bendice cada mon' },
  torii: { icon: TORII, name: 'El torii', line: 'la referencia del arte: se pasa por debajo, nunca por encima' },
  onmyoji: { icon: ONMYOJI, name: 'El onmyōji', line: 'y su shikiban: lo que mueve el mundo por debajo' },
  fujin: { icon: FUJIN, name: 'Fūjin', line: 'el viento que empuja al viajero de nivel en nivel' },
  daikoku: { icon: DAIKOKU, name: 'Daikokuten', line: 'el mazo de la fortuna: cada golpe en la interfaz, un mon' },
};
